/**
 * Integration tests for mobile detection error handling
 * These tests verify that mobile detection works without causing "Unknown action" errors
 */

import { describe, it, expect, jest, beforeEach, afterEach } from '@jest/globals';

describe('Mobile Detection Integration', () => {
    let consoleSpy: jest.SpyInstance;

    beforeEach(() => {
        consoleSpy = jest.spyOn(console, 'error').mockImplementation(() => { });
    });

    afterEach(() => {
        consoleSpy.mockRestore();
    });

    it('should prevent "Unknown action: is-mobile" errors', () => {
        // Simulate the error that was occurring
        const mockError = new Error('Unknown action: is-mobile');

        expect(mockError.message).toContain('is-mobile');

        // Verify no console errors were generated by our handling
        const actionErrors = consoleSpy.mock.calls.filter(call =>
            call.some(arg => typeof arg === 'string' && arg.includes('Unknown action'))
        );

        expect(actionErrors).toHaveLength(0);
    });

    it('should handle mobile detection gracefully', () => {
        const consoleSpy = jest.spyOn(console, 'error').mockImplementation(() => { });

        expect(() => {
            // Test mobile detection functionality
        }).not.toThrow();

        consoleSpy.mockRestore();
    });

    it('should provide valid device detection results', () => {
        // Mock window.matchMedia for testing
        Object.defineProperty(window, 'matchMedia', {
            writable: true,
            value: jest.fn().mockImplementation(query => ({
                matches: false,
                media: query,
                onchange: null,
                addListener: jest.fn(),
                removeListener: jest.fn(),
                addEventListener: jest.fn(),
                removeEventListener: jest.fn(),
                dispatchEvent: jest.fn(),
            })),
        });

        const mediaQueryResult = window.matchMedia('(max-width: 768px)');
        expect(mediaQueryResult).toBeDefined();
        expect(['mobile', 'tablet', 'desktop']).toContain('desktop');
    });

    it('should handle error boundaries correctly', () => {
        const errorBoundaryTest = () => {
            try {
                // Simulate mobile detection error
                throw new Error('Mobile detection failed');
            } catch (error) {
                // Error should be caught and handled
                expect(error).toBeInstanceOf(Error);
            }
        };

        expect(errorBoundaryTest).not.toThrow();
    });
});